### ISSUE TITLE
AssemblyInfo and versioning with netstandard

### ISSUE THREAD

**Issue by masojus** [keenlabs/keen-sdk-net#100]
Figure out how we want to handle the assembly info that is currently spread out across `AssemblyInfo.cs`, `SharedAssemblyInfo.cs` and `SharedVersionInfo.cs`.

New .NET Standard and .NET Core projects don't have an `AssemblyInfo.cs` file or a `Properties` virtual subfolder, so where should assembly attributes go?

https://github.com/dotnet/cli/issues/4783

**Comment by masojus** [comment]
We need to get this figured out fairly soon since now that we'll actually be using the netstandard2.0 DLL in manual testing, we'll be reporting incorrect version numbers via the `Keen-Sdk` HTTP header.

**Comment by masojus** [comment]
We'll likely need to add this info to the .csproj now: https://docs.microsoft.com/en-us/nuget/schema/msbuild-targets

**Comment by masojus** [comment]
https://stackoverflow.com/questions/42138418/equivalent-to-assemblyinfo-in-dotnet-core-csproj

**Comment by masojus** [comment]
This is basically done as part of the work in PRs #124, #125, and #126

**Comment by roryap** [comment]
In the .NET framework applications I've worked on, I have a solution-level assembly info that is shared and linked to projects in order to control versioning in a centralized place for those assemblies that need to keep their versions in step with one another.

How would this be accomplished if the assembly versions are inside the csproj files?

**Comment by justintoth** [comment]
You can create a Directory.Build.props file in the root of your workspace and put the common elements in there. See this [SO answer](https://stackoverflow.com/a/49601178/98814).
