### ISSUE TITLE
Seems like update broke the namespaces

### ISSUE THREAD

**Issue by MarcelloLins** [keenlabs/keen-sdk-net#11]
I just updated the Keen.IO .NET SDK on Nuget and seems like it's broken.

This is the code sample that used to work :

    var projectSettings = new ProjectSettingsProvider (keenIOProjectID, keenIOMasterKey,     keenIOWriteKey, keenIOReadKey);

    var keenClient      = new KeenClient (projectSettings);

The namespaces changed, and now I can only find the "KeenClient" one, which is on the : ifunction.KeenSDK.Core namespace, which is a bit weird. I can't seem to find the following class, though : ProjectSettingsProvider.

Also, the "JSON.NET" is missing as a dependency to the Keen.IO Nuget Package, so once we pull the .dll from Nuget, it doesn't bring the JSON.NET .dll aswell.  Without the dependency the Keen.IO gets downloaded, but crashes on every call because it's missing JSON.NET dll dependency.

**Comment by davidknaack** [comment]
It sounds like you are using https://github.com/rynnwang/KeenSDK rather than https://github.com/keenlabs/keen-sdk-net. There are some significant differences in naming between the two projects.

If you installed via the NuGet package manager console you may have installed "Keen.NET" instead of "KeenClient".

There is a problem with the JSON.NET dependency though. It's included as a dependency in the package, but Visual Studio isn't pulling it. I suspect a problem with the package itself, I'll investigate and get back to you.

As a workaround you can go to the package manager console and "Install-Package Newtonsoft.Json" to add the package to your project.

**Comment by MarcelloLins** [comment]
You were right, i've been using the wrong "Nuget Package". 

Regarding the Newtonsoft Package, it is working as expected. I have removed all the dependencies from my solution, rebuild it (it failed, as expected), than I have added the proper Keen nuget package and it pulled the newtonsoft aswell.

Closing this issue.
