### ISSUE TITLE
Potential bug in EventCachePortable

### ISSUE THREAD

**Issue by willstones** [keenlabs/keen-sdk-net#21]
On line 57 of EventCachePortable.cs when initialising the Event Cache from the list of files on disk, the Event Cache is only populating the events queue if the events queue already has an item in it -  if(events.Any()).  This seems like the wrong way around and looks like it means the EventCachePortable will never load items off disk which were saved from a previous session.

Apologies if I have misunderstood this code but it looks like a bug to me.

Will

**Comment by baumatron** [comment]
I agree, it looks like the if (events.Any()) could be removed entirely, and in the normal use case any file-backed events that hadn't been sent by a previous app instance would not be added to the list of pending events.

Another odd thing about the way this class is built is that for each new EventCachePortable created, instances which potentially an app could have many of, it scans the event cache folder and adds all events to the _static_ event queue. Perhaps the bug mentioned here obscures this additional bug, but this would mean that the event queue would add a copy of each file-backed cached event for each instance of EventCachePortable created. TryTake() would then fail when trying to dequeue a duplicate event when it doesn't find the associated file. In fact, the usage of a static queue seems superfluous on the surface, since Add() always should create a new file on disk and TryTake() always attempts to read said file.

I would recommend that tests for event persistence be added for this class. I don't see any tests that cover that aspect of the class. After adding those tests, I would suggest the class be simplified by removing the queue altogether.

**Comment by willstones** [comment]
You're totally right.

I've actually abandoned EventCachePortable entirely as it has a number of threading issues with it.  For example in TryTake() it early on locks the event queue and then Dequeues an element off the queue (line 130).  It then goes on to asynchronously attempt to read the file off the disk for this event, but because it has just removed the item from the queue there is a race condition whereby if another thread tries to add an event with the same id to the queue using Add() it will loop over the queue (line 89) and potentially reuse the same file name as is currently being read on the other thread, thus resulting in a File Access error with one thread trying to open for read, while another has it open for write (which I was seeing).

And as you've pointed out the nature of the static events member is not great either.

If I had the time I'd re-write, but right now deadlines are awaiting (pun intended)!

**Comment by baumatron** [comment]
You're right, seems like there's a race condition there as well. There are a lot of areas for improvement here, thanks for all the feedback!

**Comment by masojus** [comment]
I've tagged this as `#dotnetsummer` but this might need to be rolled into the [Port Keen PCL to netstandard](https://github.com/keenlabs/keen-sdk-net/projects/2) project and perhaps broken up into a few different tasks. This cache might reference some stuff not available in netstandard2.0 or 1.6, which is one issue, but there are potentially several different threading issues here to handle too. So it might be necessary to work with only the memory-based cache at first.

**Comment by baumatron** [comment]
Problems outlined here are fixed by #121 and now in `dotnetsummer`.
